core/hwclayer: avoid missing field inizializers in libsync
To avoid following building errors:

In file included from external/IA-Hardware-Composer/common/core/hwclayer.cpp:18:
external/libdrm/libsync.h:63:24: error: missing field 'events' initializer [-Werror,-Wmissing-field-initializers]
        struct pollfd fds = {0};
                              ^
external/libdrm/libsync.h:88:33: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        struct sync_merge_data data = {0};
                                       ^
                                       {}
external/libdrm/libsync.h:88:34: error: missing field 'fd2' initializer [-Werror,-Wmissing-field-initializers]
        struct sync_merge_data data = {0};
                                        ^
3 errors generated.